CLUBS = {"Bodø/Glimt":"Bodoe Glimt",
         "Brann": "Brann",
         "Bryne": "Bryne",
         "Fredrikstad": "Fredrikstad",
         "HamKam": "Ham-Kam",
         "Haugesund": "Haugesund",
         "KFUM": "KFUM Oslo",
         "Kristiansund": "Kristiansund",
         "Molde": "Molde",
         "Rosenborg": "Rosenborg",
         "Sandefjord Fotball": "Sandefjord",
         "Sarpsborg 08": "Sarpsborg",
         "Strømsgodset": "Stromsgodset",
         "Tromsø": "Tromso",
         "Viking": "Viking",
         "Vålerenga": "Valerenga"
         }