CLUBS = {"Bodø/Glimt":"Bodoe Glimt",
         "Brann": "Brann",
         "Fredrikstad": "Fredrikstad",
         "HamKam": "Ham-Kam",
         "Haugesund": "Haugesund",
         "KFUM": "KFUM Oslo",
         "Kristiansund": "Kristiansund",
         "Lillestrøm": "Lillestrom",
         "Molde": "Molde",
         "Odd": "Odd Grenland",
         "Rosenborg": "Rosenborg",
         "Sandefjord": "Sandefjord",
         "Sarpsborg 08": "Sarpsborg",
         "Strømsgodset": "Stromsgodset",
         "Tromsø": "Tromso",
         "Viking": "Viking",
         }